### ISSUE TITLE
High ping error

### ISSUE THREAD

**Issue by Reborn5537** [Night-GUA/YuAntiCheat#4]
**_When using the OurPlay accelerator
Latency will continue to increase until you are kicked out of the server
This problem was not present in the old version 1.0.3
I also tried using the original version with the accelerator without this problem.
Please check for network-related code errors.
Please fix it in time, thanks to the developers._**
![81f7551a93433978acb4ac816e532040](https://github.com/Night-GUA/YuAntiCheat/assets/134705775/eac920ba-5ed2-41ab-9dce-493c49c65ffe)

**Comment by Reborn5537** [comment]
在使用OurPlay加速器的时候
延迟会持续增加直到被服务器踢出
在旧版本1.0.3没有这个问题
同时我也尝试用原版配合加速器都没有出现这个问题
请检测相关与网络有关的代码错误的地方
请及时修复谢谢开发者

**Comment by Reborn5537** [comment]
在使用OurPlay加速器的时候
延迟会持续增加直到被服务器踢出
在旧版本1.0.3没有这个问题
同时我也尝试用原版配合加速器都没有出现这个问题
请检测相关与网络有关的代码错误的地方
请及时修复谢谢开发者

**Comment by Night-GUA** [comment]
We are not have this bug
我们并没有此问题
